<?php

$string['pluginname'] = 'GuardianKEY';
$string['synctask'] = 'GuardianKEY task';
$string['auth_guardiankeydescription'] = 'The information below are generated automatically by a scheduled task. Check if Moodle is in your crontab and wait some minutes. Take care on changing these information.';
$string['auth_guardiankey_hashid_key'] = 'Agent ID';
$string['auth_guardiankey_hashid'] = 'Unique identification generated by the GuardianKEY engine for your Agent (Moodle instance).';
$string['auth_guardiankey_orgid_key'] = 'Organization ID';
$string['auth_guardiankey_orgid'] = 'Unique identification generated by the GuardianKEY engine for your organization.';
$string['auth_guardiankey_authgroupid_key'] = 'Auth Group ID';
$string['auth_guardiankey_authgroupid'] = 'Unique identification generated by the GuardianKEY engine for the authentication group (set of users).';
$string['auth_guardiankey_key_key'] = 'KEY';
$string['auth_guardiankey_key'] = 'Encryption key used for authentication and confidentiality';
$string['auth_guardiankey_iv_key'] = 'IV';
$string['auth_guardiankey_iv'] = 'IV for the Key.';
$string['auth_guardiankey_reverse_key'] = 'DNS reverse lookup';
$string['auth_guardiankey_reverse'] = 'Make a DNS reverse lookup for the user\'s IP address.';
$string['auth_guardiankey_salt_key'] = 'Salt';
$string['auth_guardiankey_salt'] = 'Salt used to cipher the local username and send it for intelligent analysis.';
$string['auth_guardiankeyemailsettingheader']= 'Email template settings';
$string['auth_guardiankey_emailsubject_default'] = 'Security Alert!';
$string['auth_guardiankey_emailtext_default'] = '

Your Moodle account was used to make the atypical login described below.
If you do not recognize this access as legitimate, please inform the
Moodle\'s administrator and change your password.
If you made this access, don\'t worry, just ignore this message.

  IP: [IP] ([IP_REVERSE])
  LOCATION: [CITY]
  SYSTEM: [SYSTEM]
  USER-AGENT: [USER_AGENT]
  DATE/TIME: [DATE], [TIME]

Attention: Never give your password to another person! 
We will never request your login information.

';
$string['auth_guardiankey_emailhtml_default'] = '
<html>
<head></head>
<body>
<p>Your Moodle account was used to make the atypical login described below.
If you do not recognize this access as legitimate, please inform the
Moodle\'s administrator and change your password.
If you made this access, don\'t worry, just ignore this message.</p>
<br /> <br /> 
<b>
  IP: [IP] ([IP_REVERSE])<br />
  LOCATION: [CITY]<br />
  SYSTEM: [SYSTEM]<br />
  USER-AGENT: [USER_AGENT]<br />
  DATE/TIME: [DATE], [TIME]
</b>
<br /> <br />
<p>Attention: Never give your password to another person! 
We will never request your login information.</p>
</body>
</html>
';
$string['auth_guardiankey_emailsubject_key'] = 'Email subject:';
$string['auth_guardiankey_emailsubject'] = 'The email subject for alerts sent to users.';
$string['auth_guardiankey_emailtext_key'] = 'Email text';
$string['auth_guardiankey_emailtext'] = 'The values enclosed with brackets are variables, e.g., "[IP]" (the client IP used on authentication).';
$string['auth_guardiankey_emailhtml_key'] = 'Email HTML';
$string['auth_guardiankey_emailhtml'] = 'The values enclosed with brackets are variables, e.g., "[IP]" (the client IP used on authentication).';

$string['auth_guardiankey_test_key'] = 'Testing mode';
$string['auth_guardiankey_test'] = 'Will not send e-mail to users in test mode. However, e-mails will be sent to the support address.';
$string['auth_guardiankey_supportaddr_key'] = 'Support e-mail address';
$string['auth_guardiankey_supportaddr'] = 'Alerts will all be sent to this e-mail.';


